main: parts.lost.mc.scriptexecutor.kotlin.ScriptExecutor
name: ScriptExecutor
version: ${version}
author: Jack Young
api-version: '1.13'

commands:
  scriptexecute:
    description: Executes the provides script
    aliases: se
    permission: scriptexecutor.scriptexecute