# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '**.gradle'
      - 'gradle/**'
      - '.github/workflows/gradle.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: '18'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Setting Environmental Variables
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    - name: Renaming
      run: mv ./build/libs/*.jar ${{ format('./build/libs/ScriptExecutor-{0}.jar', steps.vars.outputs.sha_short) }}
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ format('DevBuild{0}-{1}', github.run_number, steps.vars.outputs.sha_short) }}
        prerelease: true
        title: ${{ format('Development Build - {0}-{1}', steps.vars.outputs.branch, steps.vars.outputs.sha_short) }}
        files: |
          LICENSE
          build/libs/*.jar
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Latest
        path: build/libs